### ISSUE TITLE
How to use prosemeteor in my meteor app?

### ISSUE THREAD

**Issue by derdaumen** [prosemeteor/prosemirror#24]
I'd like to try prosemeteor in my app. I'm very much a meteor newbie and I've never worked with a local package before. So far I only worked with atmosphere packages.

I managed to download the code and add it as a local package to my app.
I copied the two imports from the demo:

```
import { createEmptyDoc } from './../../../api/documents/both/methods';
import { documentsColl } from './../../../api/documents/both/collection';
```

but I get an an 

```
Uncaught Error: Cannot find module './../../../api/documents/both/methods'
```

I feel embarrassed to ask this question, but how can I make these imports work?
I'd very much appreciate some help.

**Comment by ejfrancis** [comment]
hey @derdaumen 

You should be able to try it out by using similar imports as you'll see in the `/demo` directory, see the [client](https://github.com/prosemeteor/prosemirror/blob/master/demo/client/main.js) and [server](https://github.com/prosemeteor/prosemirror/blob/master/demo/server/main.js) examples

I should add that this is still a functioning proof-of-concept. If you want to play with it in your app it should work fine but it's definitely not production ready yet. You will get realtime collaboration working for free, but the main issues with it are:
1. it still doesn't clean up document sessions in memory on the server that are no longer being editd by any users
2. currently all changes are broadcasted to all clients
3. It's hardcoded to a specific version of ProseMirror, this makes dev easier because the ProseMirror api is still changing rapdily but eventually you should be able to use any version you'd like with it after ProseMirror 1.0 is released or it's api at least becomes more stable

But feel free to try it out and play with it
