### ISSUE TITLE
Permissioning System

### ISSUE THREAD

**Issue by funkyeah** [prosemeteor/prosemirror#9]
Integrators need a way to control CRUD operations of prosemeteor docs and potentially any other data we might generate about or auxillary to the docs. We could add integration with something like alanning's [meteor-roles](https://github.com/alanning/meteor-roles) which you mentioned in an earlier comment. I'm wondering if this might be higher level than we need to go. Can or should we make it the integrator's responsibility to marry it with whatever permission system they are using?

Maybe some type of hook or event system that the user can use to allow/deny each type of operation? Inside each client side callable method there could be an authorization call first:

```
Meteor.methods({
  'ProseMeteor.openDoc'({ docId }) {
    check(docId, String);
    authorized = Meteor.call('Prosemeteor.openDocPermission')
    if (authorized) {
      authorityManager.openDoc({ docId });
    }
  }
});
```

The integrator would have to define each method and return true if authorized to perform said operation. Do you think this would be unacceptable from a performance perspective? Do we have to have a cache of users and their respective permissions for each Authority? If so how would that cache get created and modified?

@ejfrancis also including your bullet list from the other thread. What do you think is still applicable?
- read-only mode
- snapshot enabled/disabled
- snapshot interval if enabled
- perhaps an option to disable collab altogether? So the user could still use the same ProseMeteor api to retrieve previous saves, load a doc onto a page, and save snapshots, it just wouldn't hook up the collab module and would save snapshots right from the user's local state

I thought adding the [security checklist](http://guide.meteor.com/security.html#checklist) from the Meteor guide in addition to the other requirements we add would be a good idea (some weren't applicable so I removed them but you might want to glance anyway):
- [ ] Implement authentication
- [x] Make sure your app doesn’t have the insecure or autopublish packages.
- [ ] Validate all Method and publication arguments, and include the [audit-argument-checks](https://github.com/meteor/meteor/tree/devel/packages/audit-argument-checks) to check this automatically.
- [x] Use Methods instead of client-side insert/update/remove and allow/deny.
- [x] Use specific selectors and filter fields in publications. (as long as we don't add publication)
- [x] Don’t use raw HTML inclusion in Blaze unless you really know what you are doing. (we always capture through the prosemirror document model and not html so should be good here right?)
- [ ] Don’t ever trust user IDs passed from the client. Use this.userId inside Methods and publications.

**Comment by ejfrancis** [comment]
> The integrator would have to define each method and return true if authorized to perform said operation. Do you think this would be unacceptable from a performance perspective?

Authorizing on each step submitted by a client would definitely bring the server to a crawl if it were hitting the db each time, I think you're on the right track with only authenticating when a user connects to a doc. 

>   Do we have to have a cache of users and their respective permissions for each Authority? If so how would that cache get created and modified?

Typically you don't want to cache auth data if possible, because if I remove a user from being able to edit a doc I want that change to reflect immediately. Maybe we could cache it, but then if a user is removed from edit permissions on the doc we force the cache to update.

Here's a couple ideas: 

---

A.Like you said, we could allow the client to provide their own auth function that we just call. So something like

```
(on the server)
ProseMeteor.authenticateMethod = ({ docId }) => {
   // do some stuff
   if (user is allowed to edit this doc) {
     return true;
   }
   return false;
}
```

When a client opens a doc, the authority calls the authenticate method and only allows it if it returned true.

---

B. Provide a method to let a client associate a userId as able to edit or view a doc, which would add the user's userId to a property on the doc in db, something like this

```
ProseMeteor.allowUserToEditDoc({ docId, userId })
```

But then question arises: how do we know who's allowed to add user's as editors, and who isn't? I'm not really sure

**Comment by funkyeah** [comment]
> Typically you don't want to cache auth data if possible, because if I remove a user from being able to edit a doc I want that change to reflect immediately. 

I don't see how we get around what is effectively cacheing if we are not checking permissions whenever the client sends steps. If you authenticate permissions only on openDoc then you've effectively cached the clients permission to do whatever with that doc and those permissions wouldn't be able to be changed... unless we either A) provide a mechanism to disconnect a specified client/user from an Authority on demand so they would have to re-openDoc and get their new permissions or B) figure out a way to authenticate submitting steps against an in-memory session

**Comment by ejfrancis** [comment]
> B) figure out a way to authenticate submitting steps against an in-memory session

That sounds best to me. 

If we went the route of just allowing the developer to provide their own auth method given a docId and userId (i.e. `ProseMeteor.authenticateMethod = ({ docId, userId }) => {}`), we could check permissions for each client when they connect and keep them in memory in the Authority. Then check against those permissions in memory on each step that's submitted. I think we'd have to provide a method to invalidate the cached permissions which would force each client to be re-authenticated the next time they submit/request steps from the Authority, and reject the connection if not authenticated. It would be up to the application developer to know that they have to call that invalidation method once they've removed permissions within their own permissions system though, which adds a little more complexity to the API. 

If we went the route of having a method to associate a userId with a doc (i.e. `ProseMeteor.allowUserToEditDoc({ docId, userId })`, then we could do the same thing of fetching permissions when a user opens a doc and keeps them in memory. Then provide a method to remove that user (i.e. `ProseMeteor.dontAllowUserToEditDoc({ docId, userId })`) which would remove it from db, remove it from the cached in the Authority, and force disconnect the user.

I'm still not sure which I prefer.

**Comment by funkyeah** [comment]
While we need to authorize things like `latestDocState` and `clientSubmitSteps` I think we are in agreement that that is not what we want to ask the integrator. You have the 'edit' role implied above. 

Do we have "roles" per se like:
- reader
- editor
- admin

Or should the integrator be asked to return:
- canCreate: true/false
- canRead: true/false
- canEdit: true/false
- canDelete: true/false

Or asked in a different way: what is the data-model of the in-memory permission system? Do you think each authority should hold the permission data for the document it covers, or a larger more central permission object that carries permissions for all docs (the latter seems harder to scale).... is embedding it in the [Authority props](https://github.com/prosemeteor/prosemirror/blob/master/lib/imports/api/authority/server/authority.js#L32) the right-place?

**Comment by funkyeah** [comment]
I played around with this a bit over the weekend. As mentioned above I was thinking that the permissions for each doc would get cached in each Authority. The methods we want to authenticate are setup in the [authority-manager ](https://github.com/prosemeteor/prosemirror/blob/master/lib/imports/api/authority/server/authority-manager.js#L31).

I'm thinking there we pass the userId into the authority call:

```
'ProseMeteor.latestDocState'({ docId }) {
  check(docId, String);
  userId = Meteor.userId()
  return self.latestDocState({ docId, userId });
},
```

and the authority-manager [latestDocState](https://github.com/prosemeteor/prosemirror/blob/master/lib/imports/api/authority/server/authority-manager.js#L84) would look more like:

```
latestDocState({ docId, userId }) {
  if (!this.authorities[docId]) {
    throw new Meteor.Error('Error');
  }
  return this.authorities[docId].latestDocState(userId);
}
```

and then the authority [latestDocState](https://github.com/prosemeteor/prosemirror/blob/master/lib/imports/api/authority/server/authority.js#L41)

```
latestDocState(userId) {
 if (this.isPublic == true) || (hasPermission(userId, 'canRead') {
  return {
    version: this.steps.length,
    docJSON: this.doc.toJSON()
  };
}
```

Does this seem like the right approach to you? Are there too many layers and/or are the functions of authority-manager and authority properly differentiated? Just want to think through the architecture of it before I go tearing things up.

**Comment by ejfrancis** [comment]
> Does this seem like the right approach to you?

Yes that all looks right to me, and we'd have to do about the same thing for the other methods as well. And you'd want to throw a `Meteor.Error` so the client could be aware of something going wrong if not authenticated

> Do you think each authority should hold the permission data for the document it covers

Yep

> Do we have "roles" per se like: ...Or should the integrator be asked to return: canCreate: true/false...

My biggest worry with authentication is that we don't cover a specific use case, since most applications have different needs. One idea I had is that we could provide an adapter layer to let anyone implement their own authentication mechanism (for if they wanted to use another db or a REST API or something else), but then we provide a default adapter that comes with ProseMeteor and just stores userIds on the doc on fields like `doc.auth.edit.allow = [userId1, userId2]`, `doc.auth.view.deny = [userId3]` or something simple like that. So you could register an auth adapter that exposes methods in a manner like this

```
ProseMeteor.registerAuthAdapter({
   allowUserToEditDoc({ userId, docId }) { ... },
   dontAllowUserToEditDoc({ userId, docId }) { ... },
   canEditDoc({ userId, docId }){ ... },
   canViewDoc({ userId, docId }){ ... },
   ...
});
```

that ProseMeteor uses internally. Then we'd provide some methods the user can use, which use the adpater's methods indrecitly when you call something like

`ProseMeteor.dontAllowUserToEditDoc({ docId, userId })`
`ProseMeteor.allowUserToEditDoc({ docId, userId })`
and the adapters `canEditDoc()`, `canViewDoc()` methods get called internally whenever a client receives/submits steps for a doc. Then it's up to the application developer to decide when they want to let a user call the `ProseMeteor.allowUserToEditDoc()` type methods

**Comment by ejfrancis** [comment]
>  Do you think each authority should hold the permission data for the document it covers,

Yup I'd like to keep all data related to a single Authority inside that Authority if possible. It'll make managing and avoiding memory leaks easier since when an Authority is done you can just delete it. 

>Do we have "roles" per se like: reader, editor, admin...Or should the integrator be asked to return: canCreate: true/false...

That's a tough question. I really like the idea of an API like `ProseMeteor.allowUserToEditDoc({ docId, userId })` because it's just easy to manage. So let's think about a couple use cases

1.

**Comment by ejfrancis** [comment]
accidentally clicked close button when trying to cancel a comment, ignore that

**Comment by funkyeah** [comment]
I've been thinking about this again and it seems like it will be quite a bit harder with your recent pull-request. With clients potentially connecting to multiple different servers depending on the docs they want to access we need to figure out how to scale the user authentication as well.

Meteor has some provision for logging into a secondary server by providing the DDP URL but I don't think this will work that well in your multi-server architecture.
- http://docs.meteor.com/api/accounts-multi.html

Forgive my ignorance, but I think of your implementation as more of a microservice approach where an entire server or servers could be dedicated purely to the management of prosemirror documents. The user would connect to as many of these servers as necessary to interact with the documents they have open.

I think the multi-server accounts functionality presumes that you would connect/login/authenticate/interact with only 1 of many servers as the whole app is scaled across said servers.

I don't think there is any presumption that the rest of the main app would also be available on each of the prosemirror servers.

Brainstorming then... Do we need a primary (authentication) server to be identified. When a user logs in they always authentication with that server. And when a new authority server spins up they DDP connect to that main server to get any auth updates?

Maybe I'm making this harder than it should be.

**Comment by ejfrancis** [comment]
> Forgive my ignorance, but I think of your implementation as more of a microservice approach where an entire server or servers could be dedicated purely to the management of prosemirror documents.

Yeah it's kind of a mix of microservice and monolith architecture. Meteor deploys using the monolith approach where users are stuck to a single server that runs the entire application for them with a session of their data in server memory. We're assuming that to be true, but using an approach similar to the [meteorhacks:cluster](https://github.com/meteorhacks/cluster) approach where your whole app runs on one server _except for a specific service_ (in our case our Authorities), which _may or may not_ live on another server. I would love if we could just say "make a few of your servers dedicated to ProseMirror", but that would go against how pretty much everyone does their Meteor hosting. Most ppl are just deploying up to Galaxy or their cloud with the whole app on every server. So I'm trying to make it so that you can just deploy to Galaxy (or your own infrastructure) the same way you have been, and ProseMirror is smart enough to load balance its in-memory sessions itself across all of your available app servers.

> Meteor has some provision for logging into a secondary server by providing the DDP URL but I don't think this will work that well in your multi-server architecture.
> 
> Brainstorming then... Do we need a primary (authentication) server to be identified

I haven't read much about Meteor AccountsMulti, I'll look into it. The way I'm picturing it though, I don't think we'd need a main authentication server. Speaking with @ellery44 about this, I think we'll want to use a claims-based approach, where the user claims to be authenticated for a doc when they open it, and on the server we verify whether or not they're allowed to view/edit that doc only one time when they connect. After that, we store their auth in memory so we just check against that for each following keystroke sent/received so we're not authenticating against the db on every keystroke. We'd need some way to remove that user's auth in memory if they were removed from the doc in the middle of editing it as well. So the application developer would authenticate the user the way they normally do, and we'd just use our custom system only for authenticating ProseMirror requests.

**Comment by eaddingtonwhite** [comment]
I would think authentication would be a basic wrapper around an independent DB and cache. Any server you are connecting can check if this request has a valid auth session for the action that is being made. If the request is making a change to the authentication then it must also flush cache and or update DB as well. Then every server running has this interface locally to DB and Cache so it doesn't matter what server you are connecting to it just needs to ask if the actions are valid and the library under the hood will fire off requests to update DB and cache.  Eventually if you had very large scale you could pull the library out into its own micro service and expose single REST api's for other nodes to take some of the orchestration load off of servers.

**Comment by ejfrancis** [comment]
Alright here's the plan:

## High Level
The package implementer can provide hooks that return `true`/`false` if a user is allowed to do certain things with a document. Authority instances will call these hooks once when a user connects, store that in memory, and run all authentication against that value. If a user has their permissions removed, for instance if in the application a user is moved to a new authentication role, you can force a doc's Authority instance to re-fetch all connected users' permissions via the configured hooks.

## Actions to be Authenticated
* view doc
* edit doc
* delete doc

# Server
## Public API on the Server

### Usage
Authentication will be configured with hooks on the server, and other methods will be exposed on the `ProseMeteorServer` instance like this:
```javascript
import { ProseMeteorServer } from 'meteor/prosemeteor:prosemirror';

const proseMeteorServer = new ProseMeteorServer({
  ...
  // configure authentication hooks
  authentication: {
        userCanViewDoc: ({ userId, docId }) => {
             // authenticate the user with any approach (REST call, DB read, etc)
            return true/false;
        }
  }
 });
```

### API
* Hooks to authenticate user actions
  * `userCanViewDoc({ userId, docId})`  - returns `Boolean` if a user can view a document
  * `userCanEditDoc({ userId, docId })` - returns `Boolean` if a user can edit a document
  * `userCanDeleteDoc({ userId, docId })` - returns `Boolean` if a user can delete a document
* Other public methods exposed to the package implementer
  * `invalidateDocAuthentication({ docId })` - forces an Authority instance to re-retrieve permissions data by re-running the methods given in the configured hooks. i.e. the Authority calls

## Changes for Authenticating in the Authority

The Authority will keep permissions data in memory like this

```javascript
{
   authentication: {
      view: {
          <userId>: true,
           ...
       },
      edit: {
            <userId>: false
       },
      delete: {
           <userId>: true
      }
   }
}
```

as @funkyeah described above, we will check against these permissions each time a user does an authenticated action, and if we don't have the permissions in memory yet we'll run the provided hook and then store its value.

### AuthorityManager
Pass userId when a user first connects to an Authority so that Authority knows which users auth data to use. Pass userId along with each authenticated action (view, edit, delete, etc.) to check permissions before allowing it.

```javascript
'ProseMeteor.latestDocState'({ docId }) {
  // pass in userId so doc knows who's viewing/editing it
  const userId = Meteor.userId()
  return self.latestDocState({ docId, userId });
},
```

### Authority
```javascript
import { userCanViewDoc } from `./../../authentication/auth-hooks`;

class Authority {
 // store all connected userIds. clean up when users disconnect
  userIds: [ ],

  // store userId on initial connection
  latestDocState ({ userId }) {
    this.userIds.push(userId);
    return {
      version: this.version(),
      docJSON: this.doc.toJSON()
  };
  
 // determine if user has permissions. retrieves permissions if not retrieved yet
 authenticateView({ userId }) {
  if (typeof this.authentication.view[userId] === 'undefined') {
       this.authentication.view[userId] = canUserViewDoc({ userId, this.docId });
  }
  return this.authentication.view[userId];
 },
 
 // force a refresh of all users' permissions
 invalidateAuthentication() {
    this.userIds.forEach((userId) => {
       this.authentication.view[userId] = canUserViewDoc({ userId, this.docId });
    });
 },

  // report auth error to client
 reportAuthError({ userId, type }) {
    this.streamerServer.emit('authorityAuthError', { userId, type });
 }

 latestDocState({ userId }) {
  if (this.authenticateView({ userId } )) {
   return {
     version: this.steps.length,
     docJSON: this.doc.toJSON()
   };
 } else {
    this.reportAuthError({ userId, type: 'view' });
  }
}
```

### AuthHooks
A class that holds the user provided authentication hooks for `userCanViewDoc`, etc..

```javascript
class AuthHooks {
    constructor() {
       this._canUserViewDoc = () => true;
     }
    get canUserViewDoc() {
       return this._canUserViewDoc;
    }
   set canUserViewDoc(value) {
     if(typeof value !== 'function') {
        // handle error
      }
      this._canUserViewDoc = value;
  }
  ....
}
export default const authHooks = new AuthHooks();

```

# Client
## Public API on the client
The client can listen for auth errors with a hook

### Usage
```javascript
import { ProseMeteorEditor } from 'meteor/prosemeteor:prosemirror';
import { Meteor } from 'meteor/meteor';

const editor = new ProseMeteorEditor({
    ...
    // let package implementer add a hook to be called on auth errors
    onAuthError: ({ userId, type, docId }) => {
       alert(`Oh no! User ${userId} isn\'t allowed to ${type} the document ${docId}`);
    }
  });
```
### API
* `onAuthError({ userId, type, docId })` - lets client handle auth errors. `type` is string like `"edit"`, `"view"`, etc.

## Changes for Handling Auth Errors
### CollabEditor
```javascript
 constructor ({
     onAuthError = () => {}         // let user provide hook. default to no-op
  })
 createEditor ({ version, docJSON }) {
    ...
    this.streamerClient.on('authorityAuthError', this.onAuthError({ userId, type, docId });
 }
```

**Comment by ejfrancis** [comment]
Plan for `invalidateDocAuthentication({ docId })`


### Public API
* provide an API on the server  that package implementor can call
  * `proseMeteorServer.invalidateDocAuthentication({ docId })`
* the public method calls `AuthorityManager.invalidateDocAuthentication()`

### AuthorityManager
* create member method in `AuthorityManager` called `invalidateDocAuthentication({ docId })`
* create a Meteor Method `ProseMeteor.invalidateDocAuthentication({ docId })` that just calls that member method
*  `invalidateDocAuthentication({ docId })` logic is as follows
   * if the specified document's Authority is on the current server
     * call the appropriate Authority's `retrieveAndStoreUserAuth()` method
   * else 
     * find which server is hosting the specified docId by querying DB
     * make a remote DDP call to the `ProseMeteor.invalidateDocAuthentication({ docId })` method on that specific server

**Comment by ejfrancis** [comment]
I've moved the invalidation to another issue #35

**Comment by ejfrancis** [comment]
Done:

* created AuthHooks class
* grab auth hooks in ProseMeteorServer constructor
* create authentication data structure in Authority constructor
* Authority retrieve and store user auth permissions data
* client collab-editor listen for auth error event
* make auth error event unique to document via event name params 
* add auth error handler in demo client/main
